version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        - ./:/opt/resources

  clickhouse:
    image: clickhouse/clickhouse-server:22.8.16.32-alpine
    # image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123" # HTTP
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/init.sql:/opt/init.sql
    tmpfs:
      - /var/lib/clickhouse

  postgres:
    container_name: 'foodinator-postgres'
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - "5432:5432"
    volumes:
    - db:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    volumes:
      - ./metabase/plugins:/plugins
      - ./metabase/data:/metabase-data
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    #   MB_DB_TYPE: clickhouse
    #   MB_DB_DBNAME: metabase
    #   MB_DB_PORT: 8123
    #   MB_DB_USER: admin
    #   MB_DB_PASS: admin
    #   MB_DB_HOST: clickhouse
    # secrets:
    #   - db_password
    #   - db_user

volumes:
  db:
    driver: local